### ISSUE TITLE
Dependency Issues: Outdated versions

### ISSUE THREAD

**Issue by RipaltaOriol** [metaapi/metaapi-python-sdk#1]
It appears that the current version of the `metaapi-ptyhon-sdk` has outdated packages that are now conflicting with other packages that (in my case) are crucial for the app (ie. `sentry-sdk`).

Are there any plans to update the current SDK version.

Some of the packages that conflict are
* `requests`
* `typing-extensions`

**Comment by Holychris56** [comment]
Please fix this ASAP. This repo is using very outdated version...

**Comment by metaapi** [comment]
Hello, a python SDK version 26.x/27.x with the updated versions is being prepared for a release and will be published in a few days.

**Comment by RipaltaOriol** [comment]
Just checked the new version and the problem still persists. This package currently uses`requests==2.24.0` instead of the latests stable `2.31.0` which then turns into further dependency issues down the line such as `urllib3`.

**Comment by metaapi** [comment]
Just FYI, the new sdk version is now on pypi

**Comment by arthur-c** [comment]
thank you @metaapi!
